// Generated by https://quicktype.io

export interface DetailedGist {
  url: string;
  forks_url: string;
  commits_url: string;
  id: string;
  node_id: string;
  git_pull_url: string;
  git_push_url: string;
  html_url: string;
  files: Files;
  public: boolean;
  created_at: string;
  updated_at: string;
  description: string;
  comments: number;
  user: null;
  comments_url: string;
  owner: Owner;
  forks: any[];
  history: History[];
  truncated: boolean;
}

export interface Files {
  "stuff.md"?: Md;
  "guide.md"?: Md;
  "create-device.md"?: Md;
  "notes.md"?: Md;
}

export interface Md {
  filename: string;
  type: string;
  language: string;
  raw_url: string;
  size: number;
  truncated: boolean;
  content: string;
}

export interface History {
  user: Owner;
  version: string;
  committed_at: string;
  change_status: ChangeStatus;
  url: string;
}

export interface ChangeStatus {
  total: number;
  additions: number;
  deletions: number;
}

export interface Owner {
  login: Login;
  id: number;
  node_id: NodeID;
  avatar_url: string;
  gravatar_id: string;
  url: string;
  html_url: string;
  followers_url: string;
  following_url: FollowingURL;
  gists_url: GistsURL;
  starred_url: StarredURL;
  subscriptions_url: string;
  organizations_url: string;
  repos_url: string;
  events_url: EventsURL;
  received_events_url: string;
  type: Type;
  site_admin: boolean;
}

export enum EventsURL {
  HTTPSAPIGithubCOMUsersTheFern2EventsPrivacy = "https://api.github.com/users/TheFern2/events{/privacy}",
}

export enum FollowingURL {
  HTTPSAPIGithubCOMUsersTheFern2FollowingOtherUser = "https://api.github.com/users/TheFern2/following{/other_user}",
}

export enum GistsURL {
  HTTPSAPIGithubCOMUsersTheFern2GistsGistID = "https://api.github.com/users/TheFern2/gists{/gist_id}",
}

export enum Login {
  TheFern2 = "TheFern2",
}

export enum NodeID {
  MDQ6VXNlcjEwMjY1Njgy = "MDQ6VXNlcjEwMjY1Njgy",
}

export enum StarredURL {
  HTTPSAPIGithubCOMUsersTheFern2StarredOwnerRepo = "https://api.github.com/users/TheFern2/starred{/owner}{/repo}",
}

export enum Type {
  User = "User",
}
